apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
  labels:
    type: web
spec:
  template:
    metadata:
      name: pyapp-pod
      labels:
        lang: python
    spec:
      containers:
      - name: pyapp-con
        image: 915551958967.dkr.ecr.ap-south-1.amazonaws.com/flask_container:nkumar
  selector:
    matchLabels:
      lang: python
---
apiVersion: v1
kind: Service
metadata:
  name: frontendsvc
spec:
  type: NodePort
  ports:
  - port:  8080
    targetPort: 8080
    protocol: TCP
  selector:
    lang: pythonI
