apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
  labels:
    type: web
spec:
  replicas: 2
  template:
    metadata:
      name: pyapp-pod
      labels:
        lang: python
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '9090'
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: lang
                operator: In
                values:
                - python
            topologyKey: "kubernetes.io/hostname"  
      containers:
      - name: pyapp-con
        image: 915551958967.dkr.ecr.ap-south-1.amazonaws.com/flask_container:nkumar1
        livenessProbe:
          httpGet:
            path: /liveness
            port: 5000
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3          
  selector:
    matchLabels:
      lang: python
---
apiVersion: v1
kind: Service
metadata:
  name: frontendsvc
spec:
  type: NodePort
  ports:
  - port:  5000
    targetPort: 5000
    nodePort: 31111
    protocol: TCP
  selector:
    lang: python
