apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    type: db
spec:
  template:
    metadata:
      name: mysql-pod
      labels:
        lang: sql
    spec:
      containers:
      - name: mysql-con
        image: 915551958967.dkr.ecr.ap-south-1.amazonaws.com/mysql_container:nkumar1   
          #imagePullPolicy: IfNotPresent
          #args: ["--default-authentication-plugin=mysql_native_password"]
          # resources: {}
          #terminationMessagePath: /dev/termination-log
          #terminationMessagePolicy: File
          #dnsPolicy: ClusterFirst
      restartPolicy: Always
        #schedulerName: default-scheduler
        #securityContext: {}
        #terminationGracePeriodSeconds: 30
  selector:
    matchLabels:
      lang: sql
---
apiVersion: v1
kind: Service
metadata:
  name: backendsvc
spec:
  type: ClusterIP
  ports:
  - port:  3306
    targetPort: 3306
    protocol: TCP
  selector:
    lang: pythonI
