apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    type: db
spec:
  replicas: 1
  template:
    metadata:
      name: mysql-pod
      labels:
        lang: sql
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
        prometheus.io/path: 'metrics'
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: lang
                operator: In
                values:
                - python
            topologyKey: "kubernetes.io/hostname"    
      containers:
      - name: mysql-con
        image: 915551958967.dkr.ecr.ap-south-1.amazonaws.com/mysql_container:nkumar
#the below command is to overcome the error Authentication plugin 'caching_sha2_password' cannot be loaded: Error loading shared library /usr/lib/mysql/plugin/caching_sha2_password
        args: ["--default-authentication-plugin=mysql_native_password"]
      restartPolicy: Always
  selector:
    matchLabels:
      lang: sql
---
apiVersion: v1
kind: Service
metadata:
  name: backendsvc
spec:
  type: ClusterIP
  ports:
  - port:  3306
    targetPort: 3306
    protocol: TCP
  selector:
    lang: sql
